version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mapbox-tile-server"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1dxcva8cy36e5"
s3_prefix = "mapbox-tile-server"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "tilebucket=\"qfes-mapbox-tiles\" endpoints=\"a.tiles.qfesanalytics.com,tiles.qfesanalytics.com\" domainname=\"tiles.qfesanalytics.com\""
