version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mapbox-tile-server-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1dxcva8cy36e5"
s3_prefix = "mapbox-tile-server-test"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "tilebucket=\"qfes-mapbox-tiles-test\" endpoints=\"test.tiles.qfesanalytics.com\" domainname=\"test.tiles.qfesanalytics.com\""
