AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Mapbox Tile Server 

  Based on Sample Sam Template
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters: 
  tilebucket:
    Default: "qfes-mapbox-tiles"
    Description: "The bucket to fetch tiles from"
    Type: "String"
    AllowedValues:
      - "qfes-mapbox-tiles"
      - "qfes-mapbox-tiles-test"
    

Resources:
  MapboxTileServerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: dist/
      Handler: index.handler 
      Runtime: nodejs14.x
      PackageType: Zip
      Architectures:
        - x86_64
      Events:
        TileRequest:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          # Properties:
            # Path: /  
            # Method: get
            # No path or method should give us a default function that handles all calls
      Policies:
        - S3ReadPolicy:
            BucketName:
              Ref: tilebucket
      Environment:
        Variables:
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: true
          BUCKET:
            Ref: tilebucket
          ENDPOINTS: b.tiles.qfesanalytics.com,tiles.qfesanalytics.com


Outputs:
  # ServerlessRestApi is an implicit HttpAPI created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/aws/serverless-application-model/blob/master/docs/internals/generated_resources.rst#http-api
  MapboxTileServerApi:
    Description: "API Gateway endpoint URL for Prod stage for Mapbox Tile Server"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
  MapboxTileSeverFunction:
    Description: "Mapbox Tile Server Function ARN"
    Value: !GetAtt MapboxTileServerFunction.Arn 
    # This is the function defined above
  MapBoxTileServerFunctionIamRole:
    Description: "Implicit IAM Role created for Mapbox Tile Server function"
    Value: !GetAtt MapboxTileServerFunctionRole.Arn
    # This is implicitly created
